---
title: Blog Post 1
subtitle: Introduction
author: Claire Duncan
date: '2022-09-10'
slug: []
categories: []
tags: []
---

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(sf)

##make map of GOP vote share by state (national) - 2020

house_party_vote_share_by_district_1948_2020 <- read_csv("house party vote share by district 1948-2020.csv")
h <- house_party_vote_share_by_district_1948_2020
 
# filter for relevant variables
R_2020 <- h %>%
    filter(raceYear == 2020) %>%
    select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  # summarize party vote share by state
    group_by(State) %>%
  # mutate Rep vote margin by state
    mutate(R_votemargin_st = (sum(RepVotes))/
                            sum(RepVotes + DemVotes),
           D_votemargin_st = (sum(DemVotes))/
                            sum(RepVotes + DemVotes)) %>%
    rename(state = State)

# load usmap
install.packages('plot_usmap')
library(usmap)

states_map <- usmap::us_map()
unique(states_map$abbr)

# plot
plot_usmap(data = R_2020, regions = "states", values = "R_votemargin_st", labels = TRUE) + 
  scale_fill_gradient(low = "white", high = "red", name = "GOP two-party voteshare margin") +
  labs(title = "GOP Vote Share by State in 2020") +
  theme_void()
```

2. create a map of Republican/Democrat voteshare margin by state and congressional district in 2014
```{r}
## map across all election years
# filter for relevant variables
R_all <- h %>%
    select(raceYear, State, district_num, district_id, RepVotes, DemVotes) %>%
  # summarize party vote share by state
    group_by(State) %>%
  # mutate Rep vote margin by state %>%
    mutate(R_votemargin_st = (sum(RepVotes))/
                            sum(RepVotes + DemVotes),
           D_votemargin_st = (sum(DemVotes))/
                            sum(RepVotes + DemVotes)) %>%
    rename(state = State)

# plot
plot_usmap(data = R_all, regions = "states", values = "R_votemargin_st") + 
  facet_wrap(facets = raceYear ~.) +
  scale_fill_gradient(low = "white", high = "red", name = "GOP two-party voteshare margin") +
  theme_void()

```

